# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('img', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('achievements', models.ManyToManyField(blank=True, to='application.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='application.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('about', models.TextField(default='')),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], default='male', max_length=255)),
                ('country', models.CharField(choices=[(b'VN', b'Vietnam'), (b'FRA', b'France'), (b'USA', b'United States of America'), (b'DEU', b'Germany')], default='DEU', max_length=255)),
                ('education', models.CharField(choices=[(b'Bach', b'Bachelor or equivalent'), (b'Mast', b'Master or equivalent'), (b'Doct', b'Doctoral or equivalent')], default='bach', max_length=255)),
                ('work', models.CharField(default='', max_length=255)),
                ('photo', models.CharField(default='', max_length=255)),
                ('rank', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('account_paypal', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
    ]
