# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170324_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.TextField(),
        ),
    ]
