# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20170327_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(default=''),
        ),
    ]
