# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20170329_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genetic_type',
            field=models.CharField(choices=[(b'novice', b'Genetic Novice'), (b'hobbyist', b'Genetic Hobbyist'), (b'specialist', b'Genetic Specialist'), (b'professional', b'Genetics Professional'), (b'moderator', b'GenoPedia Moderator')], default='novice', max_length=255),
        ),
    ]
