# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_userprofile_genetic_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'first_entry', b'Create your first entry'), (b'first_pub', b'Enter your first scientific publication'), (b'first_correct_on', b'Make your first correction on existing entries'), (b'first_forum_comment', b'Write your first forum comment'), (b'100_view_content', b'Make content that is viewed by 100 people'), (b'earn_10_credit', b'Earn 10 Euro for your participation'), (b'get_1_friend', b'Get 1 friend to sign up on Genopedia'), (b'answer_5_posts', b'Answer 5 different forum posts'), (b'delete_useless_page', b'Delete on useless page'), (b'1000_view_content', b'Make content that is viewed by 1000 people')], default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User'),
        ),
    ]
