# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20170331_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
