# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsnumber', models.CharField(default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('chromosome', models.TextField(default='')),
                ('genotype', models.TextField(default='')),
                ('science_filter', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.User')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsnumber', models.CharField(default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('chromosome', models.TextField(default='')),
                ('genes', models.TextField(default='')),
                ('publications', models.TextField(default='')),
                ('diseases', models.TextField(default='')),
                ('effects', models.TextField(default='')),
                ('science_filter', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
